### ISSUE TITLE
Command line prepended with tab character.

### ISSUE THREAD

**Issue by tekhnee** [marlonrichert/zsh-hist#7] opened 2021-01-09 23:37 UTC
Thank you for yet another excellent plugin.

Curiously, the plugin seems to cause the prepending of every command with a tab character (`\t`).

This tab is inserted both in the command line (upon pressing <kbd>Enter</kbd>) and in the history (as confirmed by `hist l`).

Any thoughts as to what the reason might be? Thank you once again.

**Comment by marlonrichert** [comment] 2021-01-10 09:18
_Every_ command line? That’s weird. Can you please try the following?
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-hist.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the problem occur then, too?

**Comment by tekhnee** [comment] 2021-01-10 09:58
@marlonrichert thank you for these troubleshooting steps.

Indeed, sourcing the plugin within a pristine shell solves the issue.

I'll try to identify the conflicting plugin—if I understand your intention correctly—and report back.

**Comment by tekhnee** [comment] 2021-01-10 10:24
UPDATE: The issue persists with the following bare-bones `.zshrc`:

```bash
export ZPLUG_HOME=~/.zplug
source $ZPLUG_HOME/init.zsh

zplug "marlonrichert/zsh-hist"
zplug load
```

In tandem with your troubleshooting steps above, this suggests that a conflict between zplug and zsh-hist is likely.

(Have been troubleshooting with both iTerm2 and Terminal.app on a Mac.)

**Comment by marlonrichert** [comment] 2021-01-10 12:31
Thanks for the info! I’ll have a look at what could be the problem.

**Comment by marlonrichert** [comment] 2021-01-10 15:06
Sorry, but I cannot reproduce this. Here's what I did:
```zsh
> brew install zplug
> cd "$(mktemp -d)"
> ZDOTDIR=$PWD HOME=$PWD PS1='%~:%?> ' PS4='+%e %N:%I %?> %_ ' zsh -f
% export ZPLUG_HOME=/usr/local/opt/zplug
% source $ZPLUG_HOME/init.zsh
% zplug "marlonrichert/zsh-hist"
% zplug load
```
And then I tried out different kinds of commands. They all work correctly for me.

**Comment by tekhnee** [comment] 2021-01-10 16:40
@marlonrichert hmm… I'm not surprised. The issue is profoundly puzzling. Removing zsh-hist from my plugins list instantly fixes the issue. (Of course this doesn't prove that zsh is responsible for the issue!) 

No less curiously, if I deliberately prefix a command with, say, N tab characters (N > 1), it is stored in the history with exactly one tab character. For a moment I hypothesized that `HIST_REDUCE_BLANKS` might be to blame, but no…

Any further thoughts would be much appreciated, though I realize that this might be specific to my setup.

**Comment by marlonrichert** [comment] 2021-01-10 19:16
Can you please do `functions -T .hist.format`, try again and paste the debug out here?

**Comment by tekhnee** [comment] 2021-01-10 20:46
@marlonrichert here you go. Your expertise in the area is much appreciated.

```
ls+.hist.format:1> setopt localoptions
+.hist.format:2> zstyle -t :hist: expand-aliases
+.hist.format:5> setopt NO_aliases
+.hist.format:7> REPLY=ls
+.hist.format:8> local -i ret=1
+.hist.format:10> functions[.tmp.]=ls
+.hist.format:11> [[ -n $'\tls' ]]
+.hist.format:12> REPLY='' ft+Tab to insert)
+.hist.format:13> local word chunk body=$'\n\tls'
+.hist.format:14> word=ls
+.hist.format:15> chunk=$'\n\tls'
+.hist.format:16> body=''
+.hist.format:17> prefix=$'\n\t'
+.hist.format:18> indent=''
+.hist.format:19> REPLY+=$'\n\tls'
+.hist.format:21> REPLY=$'\tls'
+.hist.format:22> ret=0
+.hist.format:25> [[ -v 'functions[.tmp.]' ]]
+.hist.format:26> unfunction .tmp.
+.hist.format:28> return ret
        ls
./
../
<…etc.>
```

**Comment by tekhnee** [comment] 2021-01-11 02:45
UPDATE: I migrated my `zsh` from `zplug` to `zsh-snap`. It was every minute, but this particular issue persists.

**Comment by marlonrichert** [comment] 2021-01-11 08:18
@tekhnee If you do `setopt extendedglob` and then try again, does the problem go away?

**Comment by tekhnee** [comment] 2021-01-11 08:38
@marlonrichert I meant to say that migrating was *worth every minute.

And yes indeed, `setopt extendedglob` does the trick — thank you! Is this option required by `zsh-hist`?

**Comment by marlonrichert** [comment] 2021-01-11 08:47
> And yes indeed, `setopt extendedglob` does the trick — thank you! Is this option required by `zsh-hist`?

No, it just means I need to set it inside the function. 🙂

**Comment by marlonrichert** [comment] 2021-01-11 18:13
Should be fixed now.

**Closed by marlonrichert** 2021-01-11 18:13 UTC
